### ISSUE TITLE
burndown chart setup

### ISSUE THREAD

**Issue by fabifont** [capstone-UniGate/UniGate#66]
### Task Details

- [x] dump all issues
- [x] group by milestone
- [x] divide between open and closed (and close date)
- [x] generate the graph
- [x] Advanced: group and count by hours
